### ISSUE TITLE
Error in build on Aarch64

### ISSUE THREAD

**Issue by CeleritasCelery** [mwerezak/sphinx-lang#1]
I am running on an M1 MacBook. Looking in the code, I don't understand why the types in the `language` module are cfg'ed to only `x86_64`. 

https://github.com/mwerezak/sphinx-lang/blob/f351b2298e6f02a3c02d42f288f6fba33e38716c/src/language.rs#L10-L17

This essentially makes whole project x86 only, since these types are used through out. What is the reason for that limitation? If I remove  the `cfg` limitation then the project builds and works correctly. Maybe the intention was to mark it 64-bit only?

If this project is intended to be x86_64 only, then it would be useful to add the following to the top of `lib.rs` to mark it as such.

```rust
#![cfg(target_arch = "x86_64")]
```

**Comment by schungx** [comment]
Looks like the intention is for 32/64-bit detection.  It is possible to do this via:

```rust
#[cfg(target_pointer_width = "32")]
```

**Comment by mwerezak** [comment]
That is indeed the intention. Thank you for the suggestion about `target_pointer_width`, sounds like it would be a better fit
